version: "3"

services:
   db_node_domain:
     image: mysql:${MYSQL_VERSION}
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     container_name: ${MYSQL_CONTAINER_NAME}

   wordpress:
     depends_on:
       - db_node_domain
     image: wordpress:${WP_VERSION}
     volumes:
       - ./html:/var/www/html/
       - html:/var/www/html/
     expose:
       - 80
     restart: always
     environment:
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       WORDPRESS_DB_HOST: db_node_domain:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
     container_name: ${WP_CONTAINER_NAME}
volumes:
    db_data:
    html:

networks:
  default:
    external:
      name: nginx-proxy